swagger: '2.0'
info:
  title: 鱼尾
  version: 1.0.2
  description: 鱼尾网后台基本 API 文档
  contact:
    name: Mondo
    email: mondogao@gmail.com
host: '127.0.0.0:8090'
basePath: /api/
schemes:
  - http
  - https
  - ws
paths:
  /templates:
    get:
      description: 获取模板实体列表
      tags:
        - templates
      parameters:
        - $ref: '#/parameters/pageParam'
        - $ref: '#/parameters/searchParam'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Template'
  /files:
    post:
      description: 上传文件接口
      tags:
        - files
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - $ref: '#parameters/fileParam'
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              id:
                $ref: '#/definitions/Id'
  /files/compose:
    post:
      description: 请求已上传的文件让服务器开始排版并返回已排版文件的 id
      tags:
        - files
      parameters:
        - name: files
          description: 已上传的文件与封面信息数组
          in: body
          schema:
            type: array
            items:
              $ref: '#/definitions/File'
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              fishId:
                $ref: '#/definitions/Id'
  '/fishes/{id}':
    get:
      description: 获取已经排版完毕的文件的信息
      tags:
        - fishes
      parameters:
        - $ref: '#/parameters/idPathParam'
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              id:
                $ref: '#/definitions/Id'
              previewHref:
                $ref: '#/definitions/Link'
              downloadLinks:
                type: object
                properties:
                  standard:
                    $ref: '#/definitions/DownloadType'
                  list:
                    $ref: '#/definitions/DownloadType'
  /users/signup:
    post:
      description: 创建新用户
      tags:
        - users
      consumes:
        - multipart/form-data
      parameters:
        - name: nickName
          in: formData
          description: 昵称
          type: string
          required: true
        - name: phone
          in: formData
          description: 手机号
          type: string
          required: true
        - name: verificationCode
          in: formData
          description: 验证码
          type: string
          required: true
        - name: email
          in: formData
          description: 邮箱
          type: string
          format: email
        - $ref: '#/parameters/passwordParam'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
  /users/login:
    post:
      description: 登陆
      tags:
        - users
      consumes:
        - multipart/form-data
      parameters:
        - name: userName
          description: 用户名（邮箱、手机号）
          in: formData
          type: string
          required: true
        - $ref: '#/parameters/passwordParam'
        - name: isRemembered
          description: 是否记住登陆状态
          in: formData
          type: boolean
          default: false
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
definitions:
  User:
    type: object
    properties:
      id:
        $ref: '#/definitions/Id'
  Template:
    type: object
    properties:
      id:
        $ref: '#/definitions/Id'
      title:
        type: string
      type:
        $ref: '#/definitions/Type'
      coverSrc:
        $ref: '#/definitions/Link'
      tags:
        type: array
        items:
          $ref: '#/definitions/Tag'
  Type:
    type: object
    properties:
      id:
        $ref: '#/definitions/Id'
      name:
        type: string
  Tag:
    type: string
  File:
    type: object
    properties:
      id:
        $ref: '#/definitions/Id'
  Id:
    type: string
  Link:
    type: string
    example: /assets/templates/0d9e-dfki-dfkj-eie2
  DownloadType:
    type: object
    properties:
      id:
        $ref: '#/definitions/Id'
      price:
        type: number
      downloadLink:
        $ref: '#/definitions/Link'
parameters:
  passwordParam:
    name: password
    in: formData
    description: 密码
    type: string
    format: password
    required: true
  pageParam:
    name: page
    in: query
    description: 获取大量数据时的页码
    type: integer
    format: int32
    default: 1
  searchParam:
    name: search
    in: query
    description: 搜索关键字属性
    type: string
  fileParam:
    name: file
    in: formData
    description: 文件
    type: file
    required: true
  idPathParam:
    name: id
    in: path
    description: file id
    type: string
    required: true
