swagger: '2.0'
info:
  title: 鱼尾
  version: 1.0.5
  description: 鱼尾网后台基本 API 文档
  contact:
    name: Mondo
    email: mondogao@gmail.com
host: '127.0.0.0:8090'
basePath: /api/
schemes:
  - http
  - https
  - ws
paths:
  /templates/page:
    get:
      description: 获取模板实体列表
      tags:
        - template
      parameters:
        - $ref: '#/parameters/pageParam'
        - $ref: '#/parameters/searchParam'
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              total:
                type: number
              page:
                type: number
                default: 1
              list:
                type: array
                items:
                  $ref: '#/definitions/Template'
  /files:
    post:
      description: 上传文件接口
      tags:
        - files
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - $ref: '#parameters/fileParam'
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              id:
                $ref: '#/definitions/Id'
              sign:
                $ref: '#/definitions/Sign'
  /files/comp_id:
    get:
      description: 下载文件接口
      tags:
        - files
      parameters:
        - $ref: '#/parameters/downloadParam'
      responses:
        '200':
          description: OK
          schema:
            type: object
  /compose/doc_id/template_id:
    get:
      description: 请求已上传的文件让服务器开始排版并返回已排版文件的 id
      tags:
        - compose
      parameters:
        - name: doc_id
          description: 已上传的文件id
          in: path
          required: true
        - name: template_id
          description: 模板id
          in: path
          required: true
        - name: sign
          in: body
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Fish'
  /users/register:
    post:
      description: 创建新用户
      tags:
        - users
      consumes:
        - multipart/form-data
      parameters:
        - name: tel
          in: formData
          description: 手机号
          type: string
          required: true
        - name: username
          in: formData
          description: 用户名
          type: string
          required: true
        - $ref: '#/parameters/passwordParam'
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
  /users/login:
    post:
      description: 登陆
      tags:
        - users
      consumes:
        - multipart/form-data
      parameters:
        - name: tel
          description: 手机号
          in: formData
          type: string
          required: true
        - $ref: '#/parameters/passwordParam'
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              sign:
                type: string
definitions:
  Template:
    type: object
    properties:
      id:
        $ref: '#/definitions/Id'
      title:
        type: string
      coverSrc:
        $ref: '#/definitions/Link'
      tags:
        type: array
        items:
          $ref: '#/definitions/Tag'
  Fish:
    type: object
    properties:
      comp_id:
        $ref: '#/definitions/Id'
      comp_path:
        type: string
  Sign:
    type: string
  Tag:
    type: object
    properties:
      organization:
        type: string
      degree:
        type: string
      type:
        type: string
  Id:
    type: string
  Link:
    type: string
    example: /assets/templates/0d9e-dfki-dfkj-eie2
parameters:
  passwordParam:
    name: password
    in: formData
    description: 密码
    type: string
    format: password
    required: true
  pageParam:
    name: page
    in: query
    description: 获取大量数据时的页码
    type: integer
    format: int32
    default: 1
  searchParam:
    name: search
    in: query
    description: 搜索关键字属性
    type: string
  fileParam:
    name: file
    in: formData
    description: 文件
    type: file
    required: true
  idPathParam:
    name: id
    in: path
    description: file id
    type: string
    required: true
  downloadParam:
    name: comp_id
    in: path
    description: 排版文件ID
    type: string
    required: true
